SOURCES = ../common/exceptions.c ../common/ini_parser.c ../common/utils.c client.c main.c options.c ui.c
OUT = remoteink

CFLAGS += -std=gnu99 -pedantic -Wall -Wshadow
LIBS += -lpthread

include common.mk
